### PR TITLE
Handle scroll up correctly

### LINKED ISSUE #59: Can't scroll through languages when launched in pop-up mode.
*From F-droid's support email.*

Screenshot_1641353761

### PR DESCRIPTION
**Pull request by fm-sys**
Fix glitch described in https://github.com/sakusaku3939/DeepLAndroid/issues/59#issuecomment-1008174735

fix #59

### CODE REVIEW

**Comment by sakusaku3939** [comment]
Thank you for fixing the bug!

By the way, does this pull request include a solution to the "only close when tapping a dark area" issue?

**Comment by fm-sys** [comment]
Not yet. It was more difficult than I thought. Webview and Native Android scroll components are unfortunately not 100% compatible... :-/

But I've set this PR to WIP for now, maybe I can find a working solution.

**Comment by sakusaku3939** [comment]
I got it.
If it's going to take some time, can I release a version that doesn't include these changes? (Resolved #60 and #23)

**Comment by fm-sys** [comment]
> can I release a version that doesn't include these changes? 

Yes, go ahead! We can release a second bugfix as soon as I'm ready here...

**Comment by fm-sys** [comment]
> Webview and Native Android scroll components are unfortunately not 100% compatible... :-/

Ooookay... I've tried many different code snippets which I found on the internet. The only `NestedScrollWebView` implementation which was working together with a bottom sheet is https://gist.github.com/alexmiragall/0c4c7163f7a17938518ce9794c4a5236

Do you think we can use the code for this app?

**Comment by sakusaku3939** [comment]
Hmmm... I don't know, the license is not listed.
However, given that it is published on a forkable Gist, I think you can use it if you leave the copyright notice.

Can you make a commit that includes this?

**Comment by fm-sys** [comment]
> However, given that it is published on a forkable Gist, I think you can use it if you leave the copyright notice.

From reading the Github ToS, it sounds like everybody is allowed to fork and execute uploaded code. However, we are not allowed to re-distribute code, except if the code is provided with a license which allows doing so.

Maybe it's better to create a Kotlin version "inspired" by the code provided in that gist.

**Comment by fm-sys** [comment]
I noticed that even the code of that gist will not work correctly for all cases. I really wonder why there really is absolutely no library which can handle this...?!

Anyway, I'm currently thinking about two possible solutions:
a) I finally find a way to generally handle scrolling of child elements correctly
b) We add a method to the Javascript interface to dynamically disable the popup dragability while the language selector is shown

**Comment by sakusaku3939** [comment]
Oh, really?
I was also thinking of idea b as a last resort, but I also thought it would be complicated to implement it.
I wish there was another way...

**Comment by sakusaku3939** [comment]
P.S.
On an unrelated note, I restarted a pull request by mistake. I don't know how to get it back.🙃

**Comment by fm-sys** [comment]
> P.S. On an unrelated note, I restarted a pull request by mistake. I don't know how to get it back.🙃

The draft state can be set here (if that's what you mean): 
Screenshot_20220115_084935

**Comment by fm-sys** [comment]
I'm making progress... Still not perfect, but being on a good way ;-)

**Comment by fm-sys** [comment]
From my side, I would be ready. To be honest, I don't fully understand the code myself, but it seems to work 😅

I'm also sure that quite some places could probably be simplified. On the other hand, never change a running system 😉

What do you think about the changes?

**Comment by sakusaku3939** [comment]
Good work!

I've checked, and it sometimes doesn't work correctly when scrolling when the language selector is closed.
However, this is minor compared to the bug where the language itself is not scrollable, so I think we can merge these.
Screenshot_20220117-181211

Also, I think it's possible to make Issues for this bug and fix it later.

Thank you so much! 👍

**Pull request merged**
