### PR TITLE
Optimize PNG files

### PR DESCRIPTION
**Pull request by papjul**
Optimize PNG files using `oxipng -Z -o max --strip all`.
Should make the APK slightly smaller without losing quality.

Note: the `icon.png` was actually a JPEG. So I replaced it with the other similar PNG file from the `drawable` directory.

### CODE REVIEW

**Review by sakusaku3939 — APPROVED** [review]
Thanks for optimizing the images! I didn't know that the fake .png I found in the past were still there...🫠

**Comment by sakusaku3939** [comment]
LGTM
@papjul Since there are few changes for users, may I include this one in the next release, which will be done irregularly?

**Comment by papjul** [comment]
Yes, it's a minor change ;)

**Comment by sakusaku3939** [comment]
Thanks! :rocket:

**Pull request merged**
